### ISSUE TITLE
Stable Fork?

### ISSUE THREAD

**Issue by gtny** [bonomani/devmon#1]
Bonomani,

I was just about to do a new devmon install and came across this repository. I see you've been making some changes and wonder if you consider the changes as committed to be stable. 

The last update to the code on sourceforge was about 3 years ago.

**Comment by bonomani** [comment]
Yes it should, but I just merge an snmpv3 from a for and I am checking now that there are no problems... so wait a little bit...to be sure that do not make a problem

**Comment by bonomani** [comment]
Something is boken with SNMPv3 merge, dont use latest commit : but you can take the previous one

**Comment by bonomani** [comment]
I revert this is not ready at all but I put a contrib dir for snmpV3 in case someone want to play with it,,,

**Comment by bonomani** [comment]
Not an issue: THIS IS A STABLE RELASE. Please use it!

**Comment by bonomani** [comment]
Thisis A STABLE RELASE. Please use it!
But most STABLE should be the previous TAGGED branches ! 
But currently the most STABLE is the: MASTER BRANCH (This comment will be updated if unstabilities are discovered

**Comment by roemer2201** [comment]
If this is considered to be stable, should the version in the devmon executable be adapted?

**Comment by bonomani** [comment]
Could be .

**Comment by bonomani** [comment]
Move to Q&A https://github.com/bonomani/devmon/discussions/61_
