### ISSUE TITLE
SNMP tests flakey on HPE Proliant Gen9 and above

### ISSUE THREAD

**Issue by coec** [bonomani/devmon#10]
Hi

using Xymon and devmon, the SNMP tests for HPE Proliant Gen9 are mostly clear, only occasionally green.  These work fine on our Gen5,6,7 servers (I thought we had some 8's but we don;t).

snmpwalk always succeeds.

Thanks

**Comment by bonomani** [comment]
Hi. 
This new code should detect more failures and give us more details for such a problem.
But we are still fixing for now diffenent little glitch and when I will think this is the moment I will propose you to try this code to see if we have more detailled, I will come back...

**Comment by bonomani** [comment]
Hi,
First you can (with this new code)
- You can try play with 
1. The size of the messages: increase or decrease it (MSGSIZE default to 8096 in devmon.cfg)
2. You can also try to use SNMP v1 for this specific device (xymon hosts.cfg)
I recommend that you keep an eye on the "dm" test to see if there is a change on the polling time: errors usuallly increase the polling time so when if you find good paramters this should probably decrease the polling time: Just that you know it is also possible that are incompatibilities between devices MSGSZE....and no option by now to do it by per device (should be not to difficult to add)

Also for you understanding:
- snmpwalk use the "c" net-snmp lib 
- devmon (by now) use perl SNMP_session lib that and native socket
-> They are not the same soft/lib at all, (they do no depend from each other), and they are probably not initialized with the same values ....

**Comment by coec** [comment]
Hi

I've checked and the MSGSIZE is the default 8096.  I've updated the
templates to be SNMP v1.

Not sure which code you want me to use?  Is there a diff/patch?

Thanks

**Comment by bonomani** [comment]
I propose you not to change the code for now, but to play with this parameters (we did not change a lot of things in the SNMP part of the wich seem to be your problem.)  
1. The MSGSIZE is set by default by devmon to 8096, but the default can be lower: 1472 is the maximum sur before the paquet is fragement (on a normal ethernet segment).
I already seem device that can not answer so play a little bit with that
2. Snmp v1 (in my knoldge do not use the snmp "getbulk" request. If it work It can be a problem with the getbulk request and also the size: getbulk want to transfert a large message!

I did not play a lot with those parameters, so I provide you just Ideas, that can (or not) make it working!

**Comment by coec** [comment]
Hi

It looks like dropping the test to SNMP v1 has fixed the problem.

Thank you!

**Comment by bonomani** [comment]
OK, so it is probably related to the fact that it do not use snmpbulk ... I will open a case for that and keep yours related to it

**Comment by bonomani** [comment]
I just found an SNMP package update that could resolve the problem, I just start using them.,but as I dont have the problem, I can just verify that it works for me like before and by now it seems to work... 

 **It would be great if someone that have the same problem can test-it!** and if it works better I will include them in devmon

- Installation : just put the files in following zip archive in the "devmon/modules" folder ! (the "modules" folder is in the perl path of devmon, so devmon will try to used these files first.)
[snmp.zip](https://github.com/bonomani/devmon/files/6630110/snmp.zip)

**Comment by bonomani** [comment]
The new version with SNMPv3 may not support getbulk, the code to support it is still there but as I cannot test it, i dont really know if this still work. Backup before upgarding...

**Comment by bonomani** [comment]
Hi,
I added a workaround would love to know if it works for you
Regards
Bruno

**Comment by coec** [comment]
Hi, 
Just got back to this.  Looks to be working but I keep an eye on this and update if there are issues.

Thanks

**Comment by bonomani** [comment]
Be carefull last update changes a lot of things (impossible to me know if it still work for you, as I switch back to SNMP_Session as default engine to improve stability (memory leaks) and the new snmpwalk engine is not deployed for the SNMP "C" external lib (which support SNMPv3)

**Comment by bonomani** [comment]
Seems to work well for me win Gen10
Also I did some a template for ilo (that mimics what you can have in the ilo itself.
Do not hesitate to reopen it, if you still have some issue !
