### ISSUE TITLE
Work under RHEL8

### ISSUE THREAD

**Issue by coec** [bonomani/devmon#18]
This occurs under Perl 5.26.
--- 
[root@xymon devmon]# ./devmon
Experimental keys on scalar is now forbidden at /usr/local/devmon/modules/dm_templates.pm line 907.
Type of arg 1 to keys must be hash or array (not hash element) at /usr/local/devmon/modules/dm_templates.pm line 907, near "};"
Experimental keys on scalar is now forbidden at /usr/local/devmon/modules/dm_templates.pm line 1068.
Type of arg 1 to keys must be hash or array (not private variable) at /usr/local/devmon/modules/dm_templates.pm line 1068, near "$deps) "
Compilation failed in require at /usr/local/devmon/modules/dm_config.pm line 29.
Compilation failed in require at ./devmon line 23.
BEGIN failed--compilation aborted at ./devmon line 23.
[root@xymon devmon]#
--- 

Suggested patch is (sorry I can't clone):
--- /usr/local/devmon/modules/dm_templates.pm.orig      2020-02-03 08:34:17.551832749 +0800
+++ /usr/local/devmon/modules/dm_templates.pm   2020-02-03 08:33:01.471034309 +0800
@@ -904,7 +904,7 @@
 }
 sub calc_template_test_deps {
    my $tmpl           = $_[0];
-   my @oids           = keys $tmpl->{oids};
+   my @oids           = keys %{$tmpl->{oids}};
    my $deps           = {} ;
    my $infls          = {} ;
    my %trans_data          ;   #for sort from W. Nelis
@@ -1065,7 +1065,7 @@
    my $node;

    # Precompute number of deps
-   foreach $node (keys $deps) {
+   foreach $node (keys %{$deps}) {
       $nb_deps{$node} = keys %{$deps->{$node}};
       $nb_infls{$node}  = keys %{$infls->{$node}};
    }

**Comment by bonomani** [comment]
I will remove the "Experimental keys on scalar"  in dm_template file line 907 and 1068" and I will replace by the patch provided!
Thank you

**Comment by bonomani** [comment]
Changes applyed
