### ISSUE TITLE
Devmon Tag for excluding certain tests in hosts.cfg

### ISSUE THREAD

**Issue by roemer2201** [bonomani/devmon#22]
Hello!

As far as I can see there is only a tag for running certain tests from a template, but not the other way around. I would like to filter out certain tests. This might come in handy for systems with a modular approach, where certain OIDs do not exist until a hardware module is plugged in.

Would be nice to hear back from you!

Regards

**Comment by bonomani** [comment]
Hello,

**Comment by roemer2201** [comment]
Thank you for your answer! Yes, device specific templates are always a possibility, but I do not really like this approach. 
The exclusion of test was indeed that, what I've been looking for, but the example you gave is based on the method of including all wanted tests, but not excluding unwanted ones. 

Would it be hard to create a tag like 'notests(if_col,module,...)'?

**Comment by bonomani** [comment]
I dont think it s really hard, bUt still have to manage conflict with current test implementation....I will mark this as a feature request: Thanks for the idea

**Comment by bonomani** [comment]
This is now implemented: 1.1.1.1 myserver #DEVMON:tests(!fans,temp) remove fans and temp tests !
