### ISSUE TITLE
Spanning Tree Protocol Test

### ISSUE THREAD

**Issue by roemer2201** [bonomani/devmon#23]
I implemented a first approach for a Spanning Tree Protocol test. It goes yellow if the last spanning tree topology change is younger than 3 minutes. This might need to be adjusted depending on the polling cycle of devmon.

The purpose of this is to help identify package flooding caused by STP topology changes.

On the Cisco IOS CLI one can see the origin, where the STP-TC (topology change) came from. Unfortunately I could not find an OID holding that information. Can you help out here?

Thank you in advance.

I created a branch in my fork, can you please check it out? https://github.com/roemer2201/devmon/tree/SpanningTreeProtocol

**Comment by bonomani** [comment]
I never used snmp and the SPT together but it seems that cisco as a mib. Seem to be more the current status of the SPT Bridge, but

**Comment by bonomani** [comment]
I just reread you implementation of this test and I will not integrate it like that (sorry): 
- I think you added to much information, that are not really relevant.
- The idea to warn if there is a the topological si good as this can be a probem,  like adding a switch that take become the root bridge
So do not hesitate to resubmit something, as I really appreciate your cooperation
