### ISSUE TITLE
Force overwrite clear status

### ISSUE THREAD

**Issue by roemer2201** [bonomani/devmon#24]
Dear all,

I'm writing a template where, depending on the devices physical configuration, some OIDs (leaf, not branch) might be empty. As soon as this happens, the test becomes white saying "No data.". I've tried many many configurations to force devmon to overwrite the clear status for that OID with green, but I have not found any working solution. Is this even possible? If so, how?

Thank you in advance!

Regards

Oliver

**Comment by roemer2201** [comment]
Thank you for offering you help! Check the following:

oids:
```
FexFanDescr1    : .1.3.6.1.2.1.47.1.1.1.1.2.101000534 : leaf
FexFanDescr2    : .1.3.6.1.2.1.47.1.1.1.1.2.102000534 : leaf
FexFanDescr3    : .1.3.6.1.2.1.47.1.1.1.1.2.103000534 : leaf
FexFanDescr4    : .1.3.6.1.2.1.47.1.1.1.1.2.104000534 : leaf
FexFanState1    : .1.3.6.1.4.1.9.9.117.1.4.1.1.1.101000534 : leaf
FexFanState2    : .1.3.6.1.4.1.9.9.117.1.4.1.1.1.102000534 : leaf
FexFanState3    : .1.3.6.1.4.1.9.9.117.1.4.1.1.1.103000534 : leaf
FexFanState4    : .1.3.6.1.4.1.9.9.117.1.4.1.1.1.104000534 : leaf
```
transforms:
```
FexFanStatus1 : SWITCH : {FexFanState1} 1=unknown,2=powered on,3=powered down,4=partial failure needs replacement as soon as possible
FexFanStatus2 : SWITCH : {FexFanState2} 1=unknown,2=powered on,3=powered down,4=partial failure needs replacement as soon as possible
FexFanStatus3 : SWITCH : {FexFanState3} 1=unknown,2=powered on,3=powered down,4=partial failure needs replacement as soon as possible
FexFanStatus4 : SWITCH : {FexFanState4} 1=unknown,2=powered on,3=powered down,4=partial failure needs replacement as soon as possible
```
thresholds:
```
FexFanStatus1   : red             : partial failure needs replacement as soon as possible
FexFanStatus1   : yellow        : powered down|unknown
FexFanStatus1   : green         : powered on
#FexFanStatus2-4 have similar entries
```
message:
```
{FanDescr1}: {FanStatus1.color} {FanStatus1}
{FanDescr2}: {FanStatus2.color} {FanStatus2}
{FanDescr3}: {FanStatus3.color} {FanStatus3}
{FanDescr4}: {FanStatus3.color} {FanStatus4}
```

Okay, now the problem: Either 1+2 or 3+4 get the clear state, because this oids are empty. which causes the whole test to become clear / white.

Here is what I've tried:
- Using 'BEST' transform:
```
FexFanState1Best      : BEST  : {FexFanState1} {FexFanState3}
FexFanState2Best      : BEST  : {FexFanState2} {FexFanState4}
FexFanDescr1Best      : BEST  : {FexFanDescr1} {FexFanDescr3}
FexFanDescr2Best      : BEST  : {FexFanDescr2} {FexFanDescr4}
```
- Using 'REGSUB' transform (one FexFanState1 as example) to replace empty with 100 and add 100 as "not present" in the SWITCH-transform:
```
FexFanState1Regex      : REGSUB        : {FexFanState1} /^(.*)$/100/
FexFanState1Regex     : REGSUB        : {FexFanState1} /(.+)/100/
FexFanState1Regex       : REGSUB        : {FexFanState1} /^\D/100/
FexFanState1Regex     : REGSUB        : {FexFanState1} /[^0-9]/100/
```
- Using 'MATH'-transform to force a value of zero on empty oids:
```
FexFanState1Regex     : MATH  : {FexFanState1} + 1 - 1 : 0
```

I hope I did not forget anything. Thank you once again for your help!

**Comment by bonomani** [comment]
I will do my best to help you...

1. If you have an  "Inherited error" that means that a transform rule (here FexFanStatus1 for example), herited the errror from a previous step (so here the snmpwalk) and this is because you try to poll an oid that do not exists.
2.  I understant that you try to poll "fans" from a Cisco device and try to have their status. Also you try to to poll the FRU (Field Remplacable Unit) mib this means that you want "only" to have the status of "fans" that are "replacable". Is that really what you want ? Why not having a global status ("fru status" and "entity status" if the "fru status" do not exist) of the all fans ? 
3. If this i the case you can tra

**Comment by bonomani** [comment]
A new version is released, that should resolve a lot of bugs/misbehaviour
