### ISSUE TITLE
Updating hosts.db fails while doing "readbbhosts" and using SNMPv3 ( no v3 entries made )

### ISSUE THREAD

**Issue by git4hub1** [bonomani/devmon#73]
* Please use the 👍 to show that you are affected by the same issue.
* Subscribe to receive notifications on status change and new comments. 

### Describe the bug

While doing "devmon -vvv --readbbhosts", the SNMPv3 enabled hosts will not be validated and added to hosts.db

Manual snmpwalk with right/same credentials on device works

>If it can help you you can fill the template below
### Steps to reproduce
1. Adding device to Xymon hosts.cfg, including "devmon" tag for a SNMPv3 enabled device ( SNMP v1/v2 disabled !! )
2. Remove hosts.db and run "devmon -vvv --readbbhosts"
3. Verify hosts.db for device entry

### Expected behaviour
Expect hosts.db to contain an entry similar to:
"device"_A^["ip-address"^[161^[xymon_host^[brocade^[SANswitch^[3^[^["username"^[noAuthNoPriv^[^[^[^[^[all^[^[
or
"device"^["ip-address"^[161^[xymon_host^[brocade^[SANswitch^[3^[^["username"^[authPriv^[^[^[^[^[all^[^[
(

Both are from hosts.db after modified dm_snmp.pm,but with different devmon.cfg. First is default devmon.cfg, second is modified as below

SECLEVELS=authPriv
AUTHPROTOS=SHA
PRIVPROTOS=AES
###SECLEVELS=noAuthNoPriv,authNoPriv,authPriv
###AUTHPROTOS=,MD5,SHA
###PRIVPROTOS=,DES,AES

### Actual behaviour
hosts.db do not get updated, hence devices won't populate into configuration.

### Screenshots
No screenshots, but some logging..

### Server configuration

**Operating system:**
Linux is-storaged-a.oneadr.net 3.10.0-1160.49.1.el7.x86_64

**Xymon version:**
Xymon version 4.3.28

**Perl version:**
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 44 registered patches, see perl -V for more detail)

**Devmon version:** 
devmon-v0.21.08.13

**Additional context**

==== Initial ===
No hosts.db file
No modification in dm_snmp.pm or devmon.cfg

> SECNAMES="username"
> AUTHPASSS=,"password"
> PRIVPASSS=,"password"
> 
> ###SECLEVELS=noAuthNoPriv,authNoPriv,authPriv
> ###AUTHPROTOS=,MD5,SHA
> ###PRIVPROTOS=,DES,AES

DEBUG INFORMATION:
INFOR CONF: Net-SNMP is installed and provides SNMPv2c and SNMPv3
INFOR CONF: SNMP_Session is installed and provides SNMPv1
INFOR CONF: Reading hosts.cfg
INFOR CONF: 34 new host(s) left, trying cid:'"community"' and snmp v2
ERROR SNMP(1): Bulkwalk timeout: 40[sec] (Timeout=20 * (1 + Retries=1))
ERROR SNMP(1): Bulkwalk timeout: 40[sec] (Timeout=20 * (1 + Retries=1))
ERROR SNMP(1): Bulkwalk timeout: 40[sec] (Timeout=20 * (1 + Retries=1))
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'noAuthNoPriv', authproto:'', authpass:'', privproto:'', privpass:'' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Unsupported security level (-34)
ERROR SNMP(1): Cannot do bulkwalk: Unsupported security level (-34)
ERROR SNMP(1): Cannot do bulkwalk: Unsupported security level (-34)
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'authNoPriv', authproto:'MD5', authpass:'"password"', privproto:'', privpass:'' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'authNoPriv', authproto:'SHA', authpass:'"password"', privproto:'', privpass:'' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'authPriv', authproto:'MD5', authpass:'"password"', privproto:'DES', privpass:'"password"' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'authPriv', authproto:'MD5', authpass:'"password"', privproto:'AES', privpass:'"password"' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'authPriv', authproto:'SHA', authpass:'"password"', privproto:'DES', privpass:'"password"' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'authPriv', authproto:'SHA', authpass:'"password"', privproto:'AES', privpass:'"password"' and snmp:v3
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
ERROR SNMP(1): Cannot do bulkwalk: Authentication failure (incorrect password, community or key) (-35)
INFOR CONF: 3 new host(s) left, trying cid:'"community"' and snmp v1
ERROR SNMP: snmpget "device1" (no response received)
ERROR SNMP: snmpget "device2" (no response received)
ERROR SNMP: snmpget "device3" (no response received)
INFOR CONF: DBFILE: "path"/devmon-v0.21.08.13/hosts.db
INFOR CONF: Fork with pid 27614 received signal TERM, shutting down with return code 0

No entry in hosts.db about device, v3

=== modify dm_snmp.pm ===
No hosts.db file
modification in devmon.cfg and dm_snmp.pm right after line 800 - hardcoded credentials like:
                $snmpvars{SecName}   = ""username"";
                $snmpvars{SecLevel}  = "authPriv";
                $snmpvars{AuthProto} = "SHA";
                $snmpvars{AuthPass}  = "password";
                $snmpvars{PrivProto} = "AES";
                $snmpvars{PrivPass}  = "password";

SECNAMES="username"
AUTHPASSS=,"password"
PRIVPASSS=,"password"

SECLEVELS=,authPriv
AUTHPROTOS=,SHA
PRIVPROTOS=,AES

DEBUG INFORMATION:
INFOR CONF: Net-SNMP is installed and provides SNMPv2c and SNMPv3
INFOR CONF: SNMP_Session is installed and provides SNMPv1
INFOR CONF: Reading hosts.cfg
INFOR CONF: 34 new host(s) left, trying cid:'"community"' and snmp v2
INFOR CONF: 3 new host(s) left, trying secname:'"username"', seclevel:'noAuthNoPriv', authproto:'', authpass:'', privproto:'', privpass:'' and snmp:v3
INFOR CONF: Valid new host:"device1", trying secname:'"username"', seclevel:'noAuthNoPriv', authproto:'', authpass:'', privproto:'', privpass:'' and snmp:v3
INFOR CONF: Valid new host:"device2", trying secname:'"username"', seclevel:'noAuthNoPriv', authproto:'', authpass:'', privproto:'', privpass:'' and snmp:v3
INFOR CONF: Valid new host:"device3", trying secname:'"username"', seclevel:'noAuthNoPriv', authproto:'', authpass:'', privproto:'', privpass:'' and snmp:v3
DEBUG CONF: Sending data to SNMP
DEBUG SNMP(1): Got EOF in message, attempting to thaw
DEBUG SNMP(1): SNMP session started: Device="device1", RemotePort=161, DestHost="ip", Version=3
DEBUG SNMP(1): Swap oid type repeaters:1->0 non-repeaters:0->1 for device "device1"
DEBUG SNMP: Fork 1 has data for device "device1", reading it
DEBUG SNMP: Fork 1 returned complete message for device "device1"
DEBUG SNMP: Dethawing data for "device1"
DEBUG SNMP(1): Got EOF in message, attempting to thaw
DEBUG SNMP(1): SNMP session started: Device="device2", RemotePort=161, DestHost="ip", Version=3
DEBUG SNMP(1): Swap oid type repeaters:1->0 non-repeaters:0->1 for device "device2"
DEBUG SNMP: Fork 1 has data for device "device2", reading it
DEBUG SNMP: Fork 1 returned complete message for device "device2"
DEBUG SNMP: Dethawing data for "device2"
DEBUG SNMP(1): Got EOF in message, attempting to thaw
DEBUG SNMP(1): SNMP session started: Device="device3", RemotePort=161, DestHost="ip" Version=3
DEBUG SNMP(1): Swap oid type repeaters:1->0 non-repeaters:0->1 for device "device3"
DEBUG SNMP: Fork 1 has data for device "device3", reading it
DEBUG SNMP: Fork 1 returned complete message for device <device3>
DEBUG SNMP: Dethawing data for "device3"
INFOR CONF: DBFILE: "path"/devmon-v0.21.08.13/hosts.db
INFOR CONF: Fork with pid 50348 received signal TERM, shutting down with return code 0

hosts.db file updated correct with all 3 devices

### Devmon log (/var/log/devmon.log)
<details>
<summary>Devmon log</summary>

```
Insert your Devmon log here
```
</details>

**Comment by bonomani** [comment]
The debug tell us that there is an SNMP v3 failure

if you let the defaut:
SECLEVELS=noAuthNoPriv,authNoPriv,authPriv
AUTHPROTOS=,MD5,SHA
PRIVPROTOS=,DES,AES
All the possibilies will be tried: 
-> so maybe you can start with that.

**Comment by git4hub1** [comment]
Sorry - saw that the formatting actually did cut off some of the information like names, pasword, ip etc...

Will do some more testing with devmon.cfg, but first tests show.

> SECNAMES=,username
> AUTHPASSS=,password
> PRIVPASSS=,password
> 
> #SECLEVELS=authPriv
> #AUTHPROTOS=SHA
> #PRIVPROTOS=AES
> SECLEVELS=noAuthNoPriv,authNoPriv,authPriv
> AUTHPROTOS=,MD5,SHA
> PRIVPROTOS=,DES,AES

Is not returning any SNMPv3 hosts, but

> SECNAMES=,username
> AUTHPASSS=,password
> PRIVPASSS=,password
> 
> SECLEVELS=authPriv
> AUTHPROTOS=SHA
> PRIVPROTOS=AES
> #SECLEVELS=noAuthNoPriv,authNoPriv,authPriv
> #AUTHPROTOS=,MD5,SHA
> #PRIVPROTOS=,DES,AES

is returning SNMPv3 hosts as expected..

> DEVIICE^[IPADDR^[161^[xymon_host^[brocade^[SANswitch^[3^[^[USERNAME^[authPriv^[SHA^[PASSWORD^[AES^[PASSWORD^[all^[^[

**Comment by bonomani** [comment]
No problem, I tought you were doing the  SNMPv4 with and empty user (i dont think it's possible but...). So this seems strange....Can you have a look at your switch it there is a bruteforce protection ?

**Comment by bonomani** [comment]
Hello, I did not receive an answer, but there was a bug in the SNMP v3 new polling engine and you were may be impacted: (See BUG #74). I just send a fix and other improvement: Let me know if this fix it.

**Comment by git4hub1** [comment]
Hi

Sorry - have been out of the loop for a while ( busy at work ), but will fetch and test the new code
Thanks

**Comment by bonomani** [comment]
No problem and if you want that we debug that together you can also contact me and arrage a way to debug it.  https://ubiquitous-network.ch/contact/ (send me your email so I can send you mine)

**Comment by git4hub1** [comment]
Got the latest version installed, but still no joy..

first config attempt ( default ): 
```
SECNAMES=,username
AUTHPASSS=,authpass
PRIVPASSS=,privpass

#SECLEVELS=authPriv
#AUTHPROTOS=SHA
#PRIVPROTOS=AES
#SECLEVELS=,authPriv,noAuthNoPriv,authNoPriv
#AUTHPROTOS=,MD5,SHA
#PRIVPROTOS=,DES,AES
```

Then tried with
```
SECNAMES=,username
AUTHPASSS=,authpass
PRIVPASSS=,privpass

#SECLEVELS=authPriv
#AUTHPROTOS=SHA
#PRIVPROTOS=AES
SECLEVELS=,authPriv,noAuthNoPriv,authNoPriv
AUTHPROTOS=,MD5,SHA
PRIVPROTOS=,DES,AES
```


Both configs above did not populate hosts.db correctly. the snmp3v Brocade switch did not show up
Only config working is specifically
```
SECLEVELS=authPriv
AUTHPROTOS=SHA
PRIVPROTOS=AES
```

Errors thrown on the failing devices

```
[22-04-06@11:27:24] ERROR SNMP(1): Cannot do bulkwalk on device BRCD: Unsupported security level (-34)
[22-04-06@11:27:24] ERROR SNMP(1): Cannot do bulkwalk on device BRCD: Authentication failure (incorrect password, community or key) (-35)
[22-04-06@11:27:24] DEBUG SNMP(1): Debug 0
[22-04-06@11:28:04] ERROR SNMP: snmpget2 BRCD (no response received)
```

Running snmpwalk with "v3" manually on the Brocade switch works ok,

**Comment by bonomani** [comment]
Hi, 
I dont know exactly what is happening: 
Unsupported security level (-34): mean that the security level is not supported: this can be expexted; as we try to discover what is supported.
Cannot do bulkwalk on device BRCD: Authentication failure: This can also be normal:  SECNAMES=,username Means that we try and empty username and the string "username" as username: so the authentication can also fail ...

But it is not normal that it do not find a working combination......

try to make some debug: 

devmon -rea -de (i dont thing you need the -f flas as debug is alway in foreground)
or 
devmon -rea -t  -f  (trace: not sur if it is usefull in this case)

Also, I dont know why you have this: (you added them or I let some old debug code): but seem to mean the following: 

[22-04-06@11:27:24] DEBUG SNMP(1): Debug 0 
-> DEBUG SNMP(1) your are in the thread 1 (alway only 1 thread for discovery, but you are in the snmppolling process), debug set to 0: no debug
[22-04-06@11:28:04] ERROR SNMP: snmpget2 BRCD (no response received)
-> your are not anymore in the thread 1: but back in the main process and you did not receivce any answer: I dont know if it is really normal...

**Comment by git4hub1** [comment]
Hi

Have been "out of office" for some weeks now - vacation and other business, but back and will try to do some more debugging, but resources are quite limited these days due to other projects :-(

However, did one quick "test" today, and using the "default" configuration like


```
SECNAMES=,MyUser
AUTHPASSS=,AuthPass
PRIVPASSS=,PrivPass
#
##SECLEVELS=authPriv
##AUTHPROTOS=SHA
##PRIVPROTOS=AES
SECLEVELS=,authPriv,noAuthNoPriv,authNoPriv
AUTHPROTOS=,MD5,SHA
PRIVPROTOS=,DES,AES
```

...it seems to find right combination  of Auth, Priv, Sec and snmp when running

`devmon -rea -de`

```
[22-05-03@11:06:07] INFOR CONF: Valid new host:MyBrocadeSAN, trying secname:'MyUser', seclevel:'authPriv', authproto:'SHA', authpass:'AuthPass', privproto:'AES', privpass:'PrivPass' and snmp:v3
[22-05-03@11:06:07] DEBUG CONF: Sending data to SNMP
[22-05-03@11:06:07] DEBUG SNMP(1): Got EOF in message, attempting to thaw
[22-05-03@11:06:07] DEBUG SNMP(1): SNMP session started: Device=MyBrocadeSAN, RemotePort=161, DestHost=10.20.30.40, Version=3
[22-05-03@11:06:07] INFOR SNMP(1): Doing bulkwalk
[22-05-03@11:06:07] ERROR SNMP(1): Cannot do bulkwalk on device MyBrocadeSAN: Authentication failure (incorrect password, community or key) (-35)
[22-05-03@11:06:07] DEBUG SNMP: Fork 1 has data for device MyBrocadeSAN, reading it
[22-05-03@11:06:07] DEBUG SNMP: Fork 1 returned complete message for device MyBrocadeSAN
```


Changing config to

```
SECNAMES=,stor2rrd
AUTHPASSS=,snmp4St0rage
PRIVPASSS=,snmp4St0rage

SECLEVELS=authPriv
AUTHPROTOS=SHA
PRIVPROTOS=AES

```

Gives following output instead.

```
[22-05-03@13:07:03] INFOR CONF: 2 new host(s) left, trying secname:'MyUser', seclevel:'authPriv', authproto:'SHA', authpass:'AuthPass', privproto:'AES', privpass:'PrivPass' and snmp:v3
[22-05-03@13:07:03] INFOR CONF: Valid new host:MyBrocadeSAN, trying secname:'MyUser', seclevel:'authPriv', authproto:'SHA', authpass:'AuthPass', privproto:'AES', privpass:'PrivPass' and snmp:v3
[22-05-03@13:07:03] DEBUG CONF: Sending data to SNMP
[22-05-03@13:07:03] DEBUG SNMP(1): Got EOF in message, attempting to thaw
[22-05-03@13:07:03] DEBUG SNMP(1): SNMP session started: Device=MyBrocadeSAN, RemotePort=161, DestHost=10.20.30.40, Version=3
[22-05-03@13:07:03] INFOR SNMP(1): Doing bulkwalk
[22-05-03@13:07:03] INFOR SNMP(1): Swap polled oid type repeaters:1->0 non-repeaters:0->1 for device MyBrocadeSAN
[22-05-03@13:07:03] DEBUG SNMP(1): Found 1/1 oids for device MyBrocadeSAN
[22-05-03@13:07:03] DEBUG SNMP: Fork 1 has data for device MyBrocadeSAN, reading it
[22-05-03@13:07:03] DEBUG SNMP: Fork 1 returned complete message for device MyBrocadeSAN
[22-05-03@13:07:03] DEBUG SNMP: Dethawing data for MyBrocadeSAN
```

Current version is v0.21.09 according to changelog

```
Devmon v0.21.09
Changes since v0.21.08
  Stabilyze SNMPv3 (thanks to Stef Coene)
```

**Comment by bonomani** [comment]
Sorry, I was also very busy, but thanks for the feedback, I will look at it!

**Comment by bonomani** [comment]
The problem is related to a Net-SNMP bug: https://github.com/net-snmp/net-snmp/issues/133
-> The perl object is not clear when out of the scope as it should
-> The credentail are not updated
We created a workaround for it
