### ISSUE TITLE
"Undefined" state reported 

### ISSUE THREAD

**Issue by OliverTUBAF** [bonomani/devmon#75]
Dear Bonomani,

there is another difference between legacy devmon and the version from this fork. We have a template for the Cisco 2960X series as an example, but other template show the same behavior. The new devmon reports a lot of "NaN", probably caused by division by zero or maybe due to division by "null"/"nil" (basically empty value). Unfortunately the devmon trace does not show any error messages, so I think, it's "working as designed". These are screenshots from new devmon:

![2022-04-06_10h05_53](https://user-images.githubusercontent.com/86062666/161935017-488b5674-ebeb-4d8a-a30b-27e65d46e4e8.png)
![2022-04-06_10h06_23](https://user-images.githubusercontent.com/86062666/161935064-e9b56881-0ca5-40e7-a90c-d79fac1c95a9.png)
![2022-04-06_10h06_45](https://user-images.githubusercontent.com/86062666/161935084-40338515-82f9-42b0-871f-d6f26ef65b21.png)

On the old devmon querying the same device with the same template the result looks like this:
![2022-04-06_10h49_07](https://user-images.githubusercontent.com/86062666/161936015-da72197c-1689-46b8-834b-eea5d9168dd3.png)
![2022-04-06_10h49_26](https://user-images.githubusercontent.com/86062666/161936027-9babcc0d-be51-4c1b-9f79-f4e8ae53096e.png)
![2022-04-06_10h50_07](https://user-images.githubusercontent.com/86062666/161936040-4b4946fb-9576-46c1-be99-d36db09b8e62.png)

My guess is there is something different now with the MATH oder DELTA transform, please have a look at the transform file from the template:

```
# cat transforms 
# Get bit speed delta (so we dont have to provide custom delta limit)
ifInOps         : DELTA         : {ifInOctets}
ifOutOps        : DELTA         : {ifOutOctets}
# Convert our octets delta into bits per second
ifInBps         : MATH          : {ifInOps} x 8
ifOutBps        : MATH          : {ifOutOps} x 8
# Do delta transform on all error counters
ifInEps		: DELTA		: {ifInErrors}
ifOutEps	: DELTA		: {ifOutErrors}
# Perform error to traffic percentage calculations
ifInErrPct	: MATH		: ({ifInEps} / {ifInBps}) x 100
ifOutErrPct	: MATH		: ({ifOutEps} / {ifOutBps}) x 100
# Create an alias in a bracketed box, or nothing if alias is blank
ifAliasBox      : REGSUB        : {ifAlias} /(\S+.*)/ [$1]/
```

Then interesting part is, that the ports showing the NaN / undefined messages are in state "admin down". (The exeption files for this template is the same on both devmon versions.)

I can provide further details, if needed, like trace logs. 

Regards

EDIT1:

Changing from "auto" to "session" in dm_config.pm (line 246) shows the same behavior.

**Comment by bonomani** [comment]
Hi Oliver, 
You are right the new devmon reports now a "NaN", when there is a division by zero: this is now expected and this changed from previous version.
- In this case setting that to green is "correct", but a division by zero is an "exception" and should be treated as such.
So now, when a division by zero occurs the value is set to NaN and the color is set to the : which meam "state disable"
Also when a test is set to "disable", no further calculation can be made, so all further result will be NaN and color "blue" 
 
We have a culculus that cannot be performed, but is it normal or is it a problem?
In this case it is normal: so we can use the "thresholds" file to treat this case:  these are 2 possibilities that you can use to change the color:

ifInErrPct	    : clear         : NaN   : 
ifOutErrPct   : clear         : NaN   : 

or 
 
ifInErrPct	    : green         :  NaN   : 
ifOutErrPct   : green         : NaN   : 
 
I like "clear" : in Xymon "clear" means "no report", I find this fit also well in this case as we do not calculate anything: . Also the color of clear is grey which is not aggressive as "blue" color: This also allow me also to see there is not any trafic on this port. Of course this does not disable the test. As soon as we have some trafic, we do the calculation and test the threshold as normally,

I also completly redesign those templates has there was multiple problems: the biggest one:  
1. Error are in packets, but traffic is in bit...so how can we compare bits and packets: this formula is not correct (or I dont understand it): "ifInErrPct	: MATH : ({ifInEps} / {ifInBps}) x 100"
1 packet can contains 21 ...to...1500 bytes, so 188 ...to... 12'000 bits. So we cannot compare different things this does not mean anything

You can have a look at the new template: cisco-2960X on the template folder

UNDEFINED generally means that there is a problem  (generally a leaf of branch oid mib that dont have an information:  This UNDEFINED value is propagate to the next calculs (again we cannot calculate with an undefined value) 

This seems to me very strange, could be a bug.....

Maybe you dont know but you can do a debug (you can let devmon run)

./devmon -p device=if_err -de 
or 
./devmon -o=xymon://stdout -m stat=xymon://stdout -m iphost=device  -m test=if_err -f -de
(this run multiple times: needed if DELTA transform is used)

And you can also change "de"  to "t" debug to trace (more verbose)
with those debug you can follow all the transformation of these values for a specific device and for a specific test.

**Comment by bonomani** [comment]
Should be fixed now
