### ISSUE TITLE
Experimental keys on scalar is now forbidden at ...dm_snmp.pm

### ISSUE THREAD

**Issue by ivanzzillo** [bonomani/devmon#78]
I am installing **_"devmon"_** to add snmp monitoring to Xymon and when i try to run **_".../devmon/devmon --readbbhosts"_** i get the following **_"Error"_**:

Experimental keys on scalar is now forbidden at .../devmon/modules/dm_snmp.pm line 818.
Type of arg 1 to keys must be hash or array (not hash element) at .../devmon/modules/dm_snmp.pm line 818, near "} ) "
Experimental keys on scalar is now forbidden at .../devmon/modules/dm_snmp.pm line 820.
Type of arg 1 to keys must be hash or array (not hash element) at .../devmon/modules/dm_snmp.pm line 820, near "} )"
Compilation failed in require at .../devmon/devmon line 21.
BEGIN failed--compilation aborted at .../devmon/devmon line 21 (#1)
    (F) An experimental feature added in Perl 5.14 allowed each, keys,
    push, pop, shift, splice, unshift, and values to be called with a
    scalar argument.  This experiment is considered unsuccessful, and
    has been removed.  The postderef feature may meet your needs better.

Uncaught exception from user code:
        Experimental keys on scalar is now forbidden at .../devmon/modules/dm_snmp.pm line 818.
        Type of arg 1 to keys must be hash or array (not hash element) at .../devmon/modules/dm_snmp.pm line 818, near "} ) "
        Experimental keys on scalar is now forbidden at .../devmon/modules/dm_snmp.pm line 820.
        Type of arg 1 to keys must be hash or array (not hash element) at .../devmon/modules/dm_snmp.pm line 820, near "} )"
        Compilation failed in require at .../devmon/devmon line 21.
        BEGIN failed--compilation aborted at .../devmon/devmon line 21._

The details of my devmon installation are as follows:

- The latest devmon version: 0.22.06.
- A single-node server installation.
- The same server as the Xymon server (v4.3.28).
- Perl version: v5.28.1.

I have been googling but I have not been able to find a solution... could you give me a hand?
                         
Thank you very much in advance

**Comment by bonomani** [comment]
Sorry, this is my fault, as I introduce this problem with previous commit. 
-This is due to latest version of perl (that I dont use now, but will use soon) that remove an experimental feature
I did make some change to correct it: Thank you  very much to have reported this problem!
You can simply just redownload devmon/module/dm_snmp.pm 
Let me know if it is working now ?

**Comment by ivanzzillo** [comment]
I downloaded the file with the latest modification and it is already working fine! 

Thank you very much for the quick solution.

**Comment by bonomani** [comment]
Thanks  Ivanzzillo !
If you make some template: share them: I will have a look and I can may optimzed them or just tell you what I think!
You can always create a issue request for whatever you want! or send me an email directly on www.ubiquitous-network.ch
Also there are probably "unclear" things so feel free to comment everything you want!
Many thanks for your issue report!
