### ISSUE TITLE
Move work-in-progress code to development branch

### ISSUE THREAD

**Issue by wnelis** [bonomani/devmon#89]
The published versions of the Perl modules do contain large chunks of dead code, often labeled in a comment section as 'work in progress' (WIP). Please remove those dead code sections from the published, main branch and move them into a development branch.

**Comment by bonomani** [comment]
Hi Wim, 
Will try to do it but quite busy and not very confortable with git, be patient.

**Comment by bonomani** [comment]
Hi I finished a lot of cleaning.
I am always looking for some help, so would be very happy to work with you! If you have some ideas let me know!
Regards
