### ISSUE TITLE
Parsing DEVMON: tag for cid() ip() port() and model() sometimes remove the following separator

### ISSUE THREAD

**Issue by jezzaaa** [bonomani/devmon#91]
* Please use the 👍 to show that you are affected by the same issue.
* Subscribe to receive notifications on status change and new comments. 

### Describe the bug

The devmon program, when run in "--readbbhosts" mode, incorrectly parses the DEVMON: tag from hosts.cfg.

Example: DEVMON: tag has `model(cisco),cid(public),ip(10.0.0.161)`, then the comma after cid() is stripped before parsing, causing the model() and ip() options to be merged into `model(cisco)ip(10.0.0.161)` without the comma. Subsequent parsing detects the model() option, but the ip() option is not recognised due to there being no comma having being stripped by the code that detects cid().

Devmon logs the message:

`2023-10-09T11:00:13.759+1100|ERROR|config   |30898|1778|Unknown devmon option (ip(10.0.0.161)) on line 2 of /etc/xymon/hosts.cfg`

If cid() is the last entry, then this problem doesn't occur, because there are no commas after it.

Other options (ip(), port(), model()) have the same problem, in that they impact some options that follow them, because they parse/strip the options list in the same way.
 
>If it can help you you can fill the template below
### Steps to reproduce
1. Create an entry in hosts.cfg that works correctly with a DEVMON: tag.
2. Add a cid() option and an ip() option to the end of the DEVMON: tag.
3. Run devmon with the "--readbbhosts" and "-debug" options, and search for "ERROR" entries, and see that the program bails with the error `Unknown devmon option (ip(10.0.0.161))`

### Expected behaviour
The cid() option should work anywhere in the DEVMON tag.

### Actual behaviour
The cid() option when not used last, can affect some options that follow.

### Server configuration

RHELv7.9

Xymon v4.3.30

Perl v5.16.3

Devmon v0.22.06 (code has not changed in Github version)

**Additional context**

### Devmon log (/var/log/devmon.log)
<details>
<summary>Devmon log</summary>

```
2023-10-09T11:00:13.759+1100|ERROR|config   |30898|1778|Unknown devmon option (ip(10.0.0.161)) on line 2 of /etc/xymon/hosts.cfg
```
</details>

**Comment by bonomani** [comment]
Just push an update, let me know if it works! And many thanks for reporting problems

**Comment by jezzaaa** [comment]
Thanks. Unable to test right away, but I'll try to test during the week and get back.

**Comment by bonomani** [comment]
When you want and do not hesitate to ask me for help
And thank you very much for all the feedback
