### ISSUE TITLE
SNMPTIMEOUT is in devmon.cfg but has been renamed to SNMP_MAX_TIMEOUT in code

### ISSUE THREAD

**Issue by jezzaaa** [bonomani/devmon#93]
### Describe the bug

The file devmon.cfg has this section (near the end of the file):

```
# SNMPTRIES: Number of attempts an SNMP query will make before it gives
# up.  More than 3 or so might be overkill here
# [DEFAULT: 2] (must be greater than 0)
#SNMPTRIES=2
```

When I set SNMPTRIES, devmon fails with this message:

`Unknown option 'snmptries' in config file, line 167`

I used this setting with a previous verison of devmon, so the code seems to have been changed.

>If it can help you you can fill the template below
### Steps to reproduce
1. edit devmon.cfg and add SNMPTRIES=2
2. run devmon
3. inspect logfile to see message about unknown option

### Expected behaviour
Adding config option according to comments that describe it in the configuration file should produce the described behaviour.

### Actual behaviour
Adding config option according to comments that describe it in the configuration file causes devmon to fail.

### Server configuration

**OS** RHELv7

**Xymon version:** v4.3.30
**Perl version:**

**Devmon version:** current devmon-main branch

### Devmon log (/var/log/devmon.log)
<details>
<summary>Devmon log</summary>

```
2024-03-07T13:36:14.089+1100|FATAL|config   |46026|1381|Unknown option 'snmptries' in config file, line 167

```
</details>

**Comment by bonomani** [comment]
HI Jezzaaa,
Thank you very much for reporting this. 
->I need to correct it/document it (sorry, was forgotten)
Explanation: it was removed with the last code. I am not sure, if it is still a pertinent option: so I don't know exactly what I will do)
- This option is now obsolete, but replaced by another counter (need also to document) snmp max "partial" retries  (=6)
-> To fix it: remove it from devmon.cfg (but you probably did it already! )
-> **Let me know if this creates a problem** for you, **or if you think this is an option you need**
-> I will let that open until documented and try to fix it quickly

**Comment by bonomani** [comment]
Hi Jezzaaa,

I did update the configuration file with current variable and default
I change also the behaviour so in that it warn abour unkown option
Let me know if you still have a bug!
And thanks for the info!
